name: Build DeviceWare

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and ldid
      run: |
        sudo apt-get update
        sudo apt-get install -y clang make git curl
        curl -L -o ldid https://github.com/theos/ldid/releases/latest/download/ldid-linux-amd64
        chmod +x ldid
        sudo mv ldid /usr/local/bin/

    - name: Download Theos
      run: |
        git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

    - name: Download iPhoneOS15.6 SDK
      run: |
        mkdir -p $HOME/theos/sdks
        git clone --depth=1 https://github.com/theos/sdks.git $HOME/temp-sdks
        cp -R $HOME/temp-sdks/iPhoneOS15.6.sdk $HOME/theos/sdks/
        rm -rf $HOME/temp-sdks

    - name: Build tweak
      run: |
        make package

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeviceWare-deb
        path: ./packages/*.deb
