name: Build DeviceWare (macOS runner)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Build dylib com xcodebuild
      run: |
        cd DeviceWare
        xcodebuild -scheme DeviceWare -configuration Release clean build \
          -sdk iphoneos \
          -arch arm64 \
          BUILD_DIR=build

    - name: Upload do artefato
      uses: actions/upload-artifact@v3
      with:
        name: DeviceWare-dylib
        path: DeviceWare/build/Release-iphoneos/DeviceWare.dylib
