name: Build .dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y perl clang make lzma

      - name: Clonar Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Instalar ldid
        run: |
          curl -L -o ldid https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid
          chmod +x ldid
          sudo mv ldid /usr/local/bin/

      - name: Baixar SDK (iOS 15.6 exemplo)
        run: |
          mkdir -p $HOME/theos/sdks
          curl -L -o $HOME/theos/sdks/iPhoneOS15.6.sdk.tar.xz https://github.com/xybp888/iOS-SDKs/releases/download/2022/iPhoneOS15.6.sdk.tar.xz
          tar -xf $HOME/theos/sdks/iPhoneOS15.6.sdk.tar.xz -C $HOME/theos/sdks

      - name: Build com Theos
        run: |
          make clean package
        env:
          THEOS: ${{ env.THEOS }}
