name: Build DeviceWare

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build tweak with xcodebuild
      run: |
        cd DeviceWare
        xcodebuild -scheme DeviceWare -configuration Release -sdk iphoneos -arch arm64 BUILD_DIR=build clean build
